### ISSUE TITLE
Accepting friend request

### ISSUE THREAD

**Issue by MajorErection** [seishun/node-steam#208]
I'm not sure how to fix this but I'm getting
TypeError: Cannot read property 'PendingInvitee' of undefined

 steamFriends.on('friend', function(steamID, relationship) {
             if (relationship == steamFriends.EFriendRelationship.PendingInvitee) {
                 console.log ('[' + steamID + '] Accepted friend request');
                 steamFriends.addFriend(steamID);
             }
             else if (relationship == steamFriends.EFriendRelationship.None) {
                 console.log('[' + steamID + '] Un-friended');
             }
         });

**Comment by seishun** [comment]
There's no "PendingInvitee" [here](https://github.com/SteamRE/SteamKit/blob/969ef6c028bb2e58b5d1699d6496c4ec2c39dbf5/Resources/SteamLanguage/enums.steamd#L66-L79).

**Comment by MajorErection** [comment]
Thanks, I was following the example in [SteamFriends](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends)

**Comment by seishun** [comment]
Thanks for reminding, fixed in c3fca6a24d413eba78daa85c8c4bfc5c4dec8596.

**Comment by MajorErection** [comment]
I'm still getting the same error
TypeError: Cannot read property 'RequestRecipient' of undefined

**Comment by seishun** [comment]
Enums are on `Steam`, not on a `SteamFriends` instance. [Enums](https://github.com/seishun/node-steam#enums).
